---
- name: Testing andrewrothstein.flyway
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'flyway -v'
      ansible.builtin.command: bash -l -c '/usr/local/flyway/flyway -v'
      changed_when: false
      register: flyway_test_output
    - name: Output of 'flyway -v'
      ansible.builtin.debug:
        msg: '{{ flyway_test_output.stdout }}'
