---
- hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - command: bash -l -c '/usr/local/flyway/flyway -v'
      register: flyway_test_output
    - name: flyway -v
      debug:
        msg: '{{ flyway_test_output.stdout }}'
