---
- name: Installing andrewrothstein.unarchivedeps
  ansible.builtin.include_role:
    name: andrewrothstein.unarchivedeps
- name: Installing andrewrothstein.bash
  ansible.builtin.include_role:
    name: andrewrothstein.bash
- name: Installing andrewrothstein.temurin
  ansible.builtin.include_role:
    name: andrewrothstein.temurin
  vars:
    temurin_app: jre
- name: Check for existing installation in {{ flyway_install_dir }}
  become: true
  become_user: root
  ansible.builtin.stat:
    path: '{{ flyway_install_dir }}'
  changed_when: false
  register: flyway_binary
- name: Downloading and installing flyway
  when: not flyway_binary.stat.exists
  block:
    - name: Downloading {{ flyway_tgz_url }}
      become: true
      become_user: root
      ansible.builtin.get_url:
        url: '{{ flyway_tgz_url }}'
        dest: '{{ flyway_tmp_tgz }}'
        checksum: '{{ flyway_checksum }}'
        mode: '644'
    - name: Unarchiving {{ flyway_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.unarchive:
        remote_src: true
        src: '{{ flyway_tmp_tgz }}'
        dest: '{{ flyway_parent_install_dir }}'
        creates: '{{ flyway_install_dir }}'
    - name: Mark flyway executable executable
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ flyway_install_dir }}/flyway'
        mode: '755'
  always:
    - name: Rm -f {{ flyway_tmp_tgz }}
      become: true
      become_user: root
      ansible.builtin.file:
        path: '{{ flyway_tmp_tgz }}'
        state: absent

- name: Linking {{ flyway_install_link_dir }} to {{ flyway_install_dir }}
  become: true
  become_user: root
  ansible.builtin.file:
    src: '{{ flyway_install_dir }}'
    dest: '{{ flyway_install_link_dir }}'
    state: link

- name: Add to default path...
  become: true
  become_user: root
  with_items:
    - f: flyway.sh
      d: /etc/profile.d
  ansible.builtin.template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m | default("644") }}'
