---
- name: check for existing installation in {{ flyway_install_dir }}
  become: yes
  become_user: root
  stat:
    path: '{{ flyway_install_dir }}'
  changed_when: false
  register: flyway_binary
- when: not flyway_binary.stat.exists
  block:
    - name: downloading {{ flyway_tgz_url }}
      become: yes
      become_user: root
      get_url:
        url: '{{ flyway_tgz_url }}'
        dest: '{{ flyway_tmp_tgz }}'
        checksum: '{{ flyway_checksum }}'
        mode: 0644
    - name: unarchiving {{ flyway_tmp_tgz }}
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: '{{ flyway_tmp_tgz }}'
        dest: '{{ flyway_parent_install_dir }}'
        creates: '{{ flyway_install_dir }}'
    - name: mark flyway executable executable
      become: yes
      become_user: root
      file:
        path: '{{ flyway_install_dir }}/flyway'
        mode: 0755
  always:
    - name: rm {{ flyway_tmp_tgz }}
      become: yes
      become_user: root
      file:
        path: '{{ flyway_tmp_tgz }}'
        state: absent

- name: linking {{ flyway_install_link_dir }} to {{ flyway_install_dir }}
  become: yes
  become_user: root
  file:
    src: '{{ flyway_install_dir }}'
    dest: '{{ flyway_install_link_dir }}'
    state: link

- name: add to default path...
  become: yes
  become_user: root
  with_items:
    - f: flyway.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
