---
- name: check for existing installation...
  become: yes
  become_user: root
  stat:
    path: '{{ flyway_install_dir }}'
  changed_when: false
  register: flyway_binary
- when: not flyway_binary.stat.exists
  block:
    - name: download...
      become: yes
      become_user: root
      get_url:
        url: '{{ flyway_tgz_url }}'
        dest: /tmp/{{ flyway_tgz }}
        checksum: '{{ flyway_checksum }}'
        mode: 0644
    - name: unarchive
      become: yes
      become_user: root
      unarchive:
        remote_src: yes
        src: /tmp/{{ flyway_tgz }}
        dest: '{{ flyway_parent_install_dir }}'
        creates: '{{ flyway_install_dir }}'
  always:
    - name: cleanup...
      become: yes
      become_user: root
      file:
        path: /tmp/{{ flyway_tgz }}
        state: absent

- name: link...
  become: yes
  become_user: root
  file:
    src: '{{ flyway_install_dir }}'
    dest: '{{ flyway_install_link_dir }}'
    state: link

- name: add to default path...
  become: yes
  become_user: root
  with_items:
    - f: flyway.sh
      d: /etc/profile.d
  template:
    src: '{{ item.f }}.j2'
    dest: '{{ item.d }}/{{ item.f }}'
    mode: '{{ item.m|default("0644") }}'
